### ISSUE TITLE
内部很多错误日志信息

### ISSUE THREAD

**Issue by paulmarkyes** [daiguadaidai/mysql-flashback#1]
首先感谢您的分享，但是代码中很多日志提示都是错误的，比如create_config.go

**Comment by daiguadaidai** [comment]
> 首先感谢您的分享，但是代码中很多日志提示都是错误的，比如create_config.go

感谢提醒, 麻烦你这边修改一下提一个pr?

**Comment by paulmarkyes** [comment]
> > 首先感谢您的分享，但是代码中很多日志提示都是错误的，比如create_config.go
> 
> 感谢提醒, 麻烦你这边修改一下提一个pr?

没问题，另外我还发现一个问题，RollBackTableMap map[string]*schema.Table 在并发读写的情况下，直接会报concurrent map read and map write；需要读写的时候加锁
