### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by paulmarkyes** [daiguadaidai/mysql-flashback#2]
RollBackTableMap map[string]*schema.Table 并发读取会报错，在读取的时候需要加锁

**Comment by daiguadaidai** [comment]
> 在读取的时候需要加锁

可以使用 sync.Map

**Comment by paulmarkyes** [comment]
嗯，也是可以的

**Comment by daiguadaidai** [comment]
> > 在读取的时候需要加锁
> 
> 可以使用 sync.Map

不过更建议在
