### ISSUE TITLE
go mod tidy无法拉取包

### ISSUE THREAD

**Issue by hellosnowy** [daiguadaidai/mysql-flashback#4]
github.com/daiguadaidai/tidb-tools 这个包拉不下来，麻烦仓库更新一下

**Comment by daiguadaidai** [comment]
> 

具体报错是什么？
我这边没有 github.com/daiguadaidai/tidb-tools  这个包的

**Comment by hellosnowy** [comment]
主要问题是这个项目的go.mod文件依赖的包版本不对
github.com/daiguadaidai/tidb v0.0.0-20190707132446-e5f2e4b8edc0
后面你修改了[tidb那个项目的代码](https://github.com/daiguadaidai/tidb/commit/025d6ddfb2de42838524aff69887db8eebc045d8)，没有同步更新这边的版本

可以本项目根目录执行
go get -u github.com/daiguadaidai/tidb
更新到最新就可以了
